### ISSUE TITLE
Highlight Open Liberty in the interactive guides

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/iguides-common#121]
Call out to users that the guides are meant for Open Liberty.

For example:

- "Enabling MicroProfile Fault Tolerance" at https://openliberty.io/guides/bulkhead.html#enabling-microprofile-fault-tolerance
    - The section title can be revised as "Enabling MicroProfile Fault Tolerance in Open Liberty"
    - "Liberty server" can be called out as "Open Liberty server"

- Sample application at https://openliberty.io/guides/bulkhead.html#great-work-you-re-done
    - Highlight that users can easily download the provided sample application and run it locally with Open Liberty
        ---> add in "...bundled with Open Liberty...." so the link says....
      "Download the sample xxx application bundled with Open Liberty on github."
    - Provide relevant instruction on how users can do so if they'd like

**Comment by mbroz2** [comment]
We already do the last bullet, but we should implement the first 3.

**Comment by mbroz2** [comment]
All completed except bullet #3.

**Comment by dmorgant** [comment]
bullet #1, #2 fixed with
https://github.com/OpenLiberty/iguide-microprofile-config/pull/222 and
https://github.com/OpenLiberty/iguide-circuit-breaker/pull/255


bullet #3 fixed in openliberty.io repo with 
https://github.com/OpenLiberty/openliberty.io/pull/884
