### ISSUE TITLE
Page cut off when switching steps

### ISSUE THREAD

**Issue by steven1046** [OpenLiberty/iguides-common#122]
When you click on a step it scrolls down to the page's title and cuts off the top of the white background. We discussed that it would be a better experience for the user if the page scrolled to the top of the white on the page.

This is the current scrollTo behavior:
![image](https://user-images.githubusercontent.com/6392944/38036422-4c8c298e-326c-11e8-9246-ac2097f5bc80.png)

This is the improved scrolling:
![image](https://user-images.githubusercontent.com/6392944/38036460-6066d76a-326c-11e8-84e6-22dde251d39b.png)

**Comment by dmorgant** [comment]
Covered with the new dual pane design.  Closing this issue.
