### ISSUE TITLE
Finish page redesign

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguides-common#145]
Combines "Great work you're done", "Contribute to this guide"

Styling changes

https://ibm.ent.box.com/folder/48384012106

PNG - https://ibm.box.com/s/0opqh62lzlzzjhtvbtwl4er82nlr8kw8
Redlines - https://ibm.box.com/s/kvo6vl77tglsi2rxu3sd3zhrtvum4wse
Assets:  https://ibm.box.com/s/om1xjqosp0ikpho4m5whk1xcd2nyja4a

![image 2](https://user-images.githubusercontent.com/6392944/40447833-769b04d0-5e99-11e8-8a71-96a33f1ee492.png)

**Comment by steven1046** [comment]
Still need to:
[] Remove the guide descriptions from the related guide cards.
[] Add a way to add guide category links
[] test the Google analytic ratings on the dev site
