### ISSUE TITLE
Use the multi-pane layout

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguides-common#148]
Try to use the multi pane layout from the static guide.

https://github.com/OpenLiberty/openliberty.io/blob/development/src/main/content/_layouts/guide-multipane.html

The layout should give you the three div columns (Table of Content, existing guide column, and the new right column)

At a minimal, we can try to adopt the new multipane layout and the right column will be blank

**Comment by steven1046** [comment]
Let me know if there are any hiccups with trying to use this layout. Some of the css for enabling multipane views in the static guides was put in guide-multipane.css and not only table-of-contents.css.

**Comment by dmorgant** [comment]
Initial drop of code to enable the multipane layout for the interactive guides was done with https://github.com/OpenLiberty/openliberty.io/issues/363.
