### ISSUE TITLE
Update all interactive guides travis.yaml script

### ISSUE THREAD

**Issue by kevinwlau** [OpenLiberty/iguides-common#150]
With the transition of the Travis build from `kinueng/openliberty.io` to `OpenLiberty/openliberty.io`, we need to update all the Travis build scripts in the interactive guides to kick off the new Travis build when PRs are merged into `dev` branch.

**Comment by mbroz2** [comment]
This is for the staging site for the interactive guides.

**Comment by k8vance88** [comment]
Closing. We don't auto build sites for any static guides.  We don't make many changes here.
