### ISSUE TITLE
Multipane Iguides: Implement section snapping

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#165]
Similar to the static guide implementation, implement section snapping for the interactive guides.  The snapping should take into account the changing of the widgets on the right-hand column to match the dominant section currently viewed on the page.

**Comment by steven1046** [comment]
I think the implementation for the static guide snapping would be the same for interactive guides given that the section structure of the middle column is very similar (the static guides can have more content than the viewport for each section as well).
