### ISSUE TITLE
Missing $ in the "Enabling <feature>" steps for httpPort

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/iguides-common#184]
The might be a problem on all our interactive guides.  We are missing a `$` in the code sample for enabling a feature.

**Example:**
https://openliberty.io/guides/microprofile-config-intro.html#enabling-microprofile-config

![image](https://user-images.githubusercontent.com/31117513/44926247-6f1f2d00-ad16-11e8-88ef-6973c4698ecf.png)

**Comment by amyreit** [comment]
Issue moved to [OpenLiberty/iguide-circuit-breaker #143](https://github.com/OpenLiberty/iguide-circuit-breaker/issues/143) via [**ZenHub**](https://www.zenhub.com/)
