### ISSUE TITLE
In single column view, editor writes over expanded TOC

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#207]
When in single column view, if an editor is in view and you click to expand the TOC, the text within the editor is written over the expanded TOC:

![image](https://user-images.githubusercontent.com/29490139/46448055-1f87b300-c753-11e8-9ba3-918d3cda1bd8.png)

**Comment by lavenal** [comment]
Fixed with this PR:
https://github.com/OpenLiberty/openliberty.io/pull/712
