### ISSUE TITLE
The opacity given to the background color of a .podContainer fails to hide browser.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#234]
In multicolumn view, with a browser, pod, and editor widget in the right column, if the window is shrunk vertically the opacity of the pod's background allows the browser window to show through the pod which is very confusing to look at: 

![image](https://user-images.githubusercontent.com/29490139/46957536-cc243780-d065-11e8-9ef7-7fc9537a5643.png)

The CSS for .podContainer is: 
![image](https://user-images.githubusercontent.com/29490139/46957615-e78f4280-d065-11e8-946c-60d28e1ffcc6.png)

I really don't think the pod should be allowed to cover up as much of the browser as it does.  I makes it near impossible to know it is there.  But in the least, the .podContainer cannot be opaque so that if it does cover up another widget then that widget's contents won't show through.

**Comment by aknguyen7** [comment]
this is relate to the #226

**Comment by lavenal** [comment]
Annie has opened an issue to set minimum height for the browser. Once she delivers the code changes, the pod would not be able to push all the way up to the url bar in the browser. Closing this issue.
