### ISSUE TITLE
Tabbing: The buttons in a disabled instruction still get focus.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#251]
When using keyboard access through the guide, we stopped tabbing to "disabled" instructions, so that they are not read (see issue #249).  However, we still have a` tabIndex = '0'`  set on the action buttons within the disabled instructions.  We not only tab to them, but we also allow Enter to be processed when on them!   Fortunately, the current instruction index is not correct and usually nothing will happen, but we should not allow tabbing to these buttons within greyed out instructions.  We should look into disabling these buttons so that no processing occurs if they are selected.

**Comment by steven1046** [comment]
Related: https://github.com/OpenLiberty/iguides-common/pull/249/files
