### ISSUE TITLE
After 'Run' selected in Editor, provide feedback to user.

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#272]
It's not always clear that pressing the Run button has a consequence.  Suggest that we should always display some kind of confirmation when the Run button is clicked.

![image](https://user-images.githubusercontent.com/29490139/49116843-6c27d000-f264-11e8-90ae-cbf9bc4fe758.png)

Display "Code updated!" message and then have it disappear after 1-2 seconds
Need to consider how this works in mobile.  It was suggested that for mobile (not just for single column, but small single column), have the message appear as an overlay that fades away after a second.

On the design slack channel, it was also suggested that "Code running" be used instead, but following a design discussion it was decided that 'Code updated' would be a better choice of words.

Priority: medium

**Comment by megmulsy** [comment]
https://ibm.box.com/s/epjwv5m1o33h2tecwy0nm495sengf450
'check' icon can be found here^^
