### ISSUE TITLE
Editor tab to include indicator when there is error in the content 

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguides-common#312]
There is a followup issue to enhance the fix for mpConfig issue #137 

https://github.com/OpenLiberty/iguide-microprofile-config-intro/issues/137

To eliminate the clicking of every editor tab to check for error or click on Run to get to the next error, it would be nice to have some type of indication in the editor tab to indicate content error is found.

**Comment by mbroz2** [comment]
We can reuse the 'red x' from the error message for the icon on the tab:
![image](https://user-images.githubusercontent.com/3076261/51704520-e2d01800-1fde-11e9-833d-d42ec30d3704.png)

**Comment by lavenal** [comment]
Instead of putting a x in the tab, the tab will be the same red color as the error.

![image](https://user-images.githubusercontent.com/25039033/53030578-b8804780-3430-11e9-9a9d-5d940720365f.png)
