### ISSUE TITLE
Reset in editor should set to the last successful code update

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/iguides-common#313]
Currently reset in editor always set to the original content. This issue is to update the code to set it to the last successful code update.

Also, when reset is selected, any error messages should be cleared for that editor since we are resetting back to a successful code update.

Update:   It was decided by the team that Reset should remain working as it currently is, resetting the code in the editor to what it looks like on entry into the step, when working with the playground steps.

**Comment by dmorgant** [comment]
To test if your Reset is working.....

1)  Add the code to the editor as instructed making some small modification (like adding an extra line in it).
2) Select 'Run' to save the new code.  It should pass validation and be saved.
3) Change the code a bit.
4) Select 'Reset'.  The code should be reverted to what it looked like in Step 2 with the correct green lines in the editor indicating which lines are editable.
