### ISSUE TITLE
Updates for the Tabbed Editor

### ISSUE THREAD

**Issue by dmorgant** [OpenLiberty/iguides-common#69]
Make the following updates for the Tabbed Editor

- [x] Fix the Tabbed Editor so that if there are more than one tabs then the tabs will stretch the whole way across the page.
- [x] Center the text in the tabs
- [x] Check if the minimal font size is acceptable for accessibility.  Find the correct algorithm to allow it to grow and shrink to maximize the filename shown in each tab.
- [x] Improve the appearance of the tabs to the editor......either make the left/right borders of the editor menu bar light grey as with the tabs and maybe put a black border under the editor menu bar to close off the editor block

**Comment by bcpswope** [comment]
Adding ID required ONLY to test view in ZenHub--will remove.
