### ISSUE TITLE
Incorrect grammar on the "contribute to this guide" page

### ISSUE THREAD

**Issue by amyreit** [OpenLiberty/iguides-common#98]
The sentence on the "contribute to this guide" page uses incorrect grammar - "Is something missing or needs to be fixed?" The subject is "something" and the verb is "is" which makes it "something is missing" and "something is needs" - should be "needing". This is used throughout interactive and static guides.

OpenLiberty/guides-common#36 is the same

**Comment by bcpswope** [comment]
Parallelism problem. I need to find this page so I can see it and I will rewrite.

**Comment by kinueng** [comment]
See this PR for the change in static guides
https://github.com/OpenLiberty/guides-common/pull/40/files

**Comment by bcpswope** [comment]
Can we close this issue?

**Comment by steven1046** [comment]
Fixed by #101
